name: CMake Build and Test on Ubuntu

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.21'

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Configure and Build with CMake
        run: |
          cmake -S . -DCMAKE_BUILD_TYPE=Debug -B build
          cmake --build build --parallel 16

      - name: Run Tests
        run: |
          # Run your custom test executable
          ./build/test_my_project

      - name: Run Python Tests
        run: |
          # Run Python tests if you have any
          pytest
