name: CMake Build on Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.21'

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Configure and Build with CMake
        run: |
          cmake -S . -DCMAKE_BUILD_TYPE=Debug -B build
          cmake --build build --parallel 16

      - name: Print Directory Contents
        run: dir .\build\bin

      - name: Run Tests on Windows
        if: runner.os == 'Windows'
        run: cmd /c .\build\bin\Debug\MyTest --output-junit test_results.xml --timeout 60 --output-on-failure
