name: CMake Build on Ubuntu

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: actions/setup-cmake@v2
        with:
          cmake-version: 3.21

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Configure and Build with CMake
        run: |
          cmake -S . -DCMAKE_BUILD_TYPE=Debug -B build
          cmake --build build --parallel 16

      - name: Run Tests
        run: |
          ctest --test-dir build -C Debug --parallel 16 --output-junit test_results.xml --timeout 60 --output-on-failure

      - name: Export Results to XML
        run: |
          mv build/debug/Testing/$(head -n 1 Testing/TAG)/Test.xml test_results.xml
