name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
           python-version: "3.10"
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Add Boost submodule
        run: |
          git submodule add https://github.com/boostorg/boost.git external/boost
          git submodule update --init --recursive
      
      - name: Install Boost on Windows
        if: runner.os == 'Windows'
        run: choco install boost-vc142

      - name: Install Boost on Ubuntu
        if: runner.os == 'Linux'
        run: sudo apt-get install -y libboost-all-dev

      #- name: Commit submodule changes
      #  run: |
      #    git config --local user.email "action@github.com"
      #    git config --local user.name "GitHub Action"
      #    git add external/boost
      #    git commit -m "Add Boost as a submodule"
      #    git push https://github.com/${{ github.repository }} HEAD:${{ github.ref }}
      #  env:
      #    GH_PAT: ${{ secrets.GH_PAT }}

      - name: Configure and Build with CMake
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Export Results to XML
        run: |
          cd build
          ctest --output-on-failure -T Test
          mv Testing/$(head -n 1 Testing/TAG)/Test.xml test_results.xml

      - name: Install Python Dependencies and Run pytest
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd /your/python/tests
          pip install -r requirements.txt  # Install dependencies if any
          pytest

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/test_results.xml
